# Generated by Django 4.2.16 on 2025-11-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.TextField(blank=True, default='[]', help_text='List of task IDs that must be completed before this task (JSON format)'),
        ),
    ]
